name: Curl Example

on:
  push:
    branches:
      - main

jobs:
  curl_job:
    runs-on: ubuntu-latest
    steps:
    - name: Make HTTP Request
      run: curl -X POST -H "Authorization: Bearer ${{WEBHOOK_TOKEN}}" -H "Content-Type: application/json" -d '{"body": "hello matrix", "msgtype": "m.text"}' '${{WEBHOOK_URL}}'